#!/usr/bin/env python3
"""CLI for the minimal reviewed-target core."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

from flashinfer_trace.runners.modal_runner import run_modal_probe
from flashinfer_trace.core.planning import (
    build_modal_probe_plan,
    build_probe_plan,
    load_approved_targets,
)
from flashinfer_trace.validation import (
    export_run_dataset,
    run_official_validate,
    update_run_report,
    validate_run,
)


def _slug_model_name(model_name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", model_name.strip()).strip("_").lower()
    return slug or "model"


def _run_dir_from_name(run: str) -> Path:
    parts = [part for part in Path(run).parts if part not in {"", "."}]
    if not parts or any(part == ".." for part in parts) or Path(run).is_absolute():
        raise SystemExit(f"ERROR: invalid run name: {run}")
    return Path("runs").joinpath(*(_slug_model_name(part) for part in parts))


def _run_config_dir(run_dir: Path) -> Path:
    return run_dir / "config"


def _run_output_dir(run_dir: Path) -> Path:
    return run_dir / "output"


def _run_modal_tmp_dir(run_dir: Path) -> Path:
    return run_dir / ".modal_tmp"


def _run_reviewed_definitions_dir(run_dir: Path) -> Path:
    return _run_config_dir(run_dir) / "definitions"


def _run_reviewed_definition_hints_dir(run_dir: Path) -> Path:
    return _run_config_dir(run_dir) / "definition_hints"


def _load_run_config(run_dir: Path) -> dict:
    path = _run_config_dir(run_dir) / "run_config.json"
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"ERROR: invalid run config {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"ERROR: run config must be a JSON object: {path}")
    return payload


def _config_value(args: argparse.Namespace, config: dict, attr: str, default=None):
    value = getattr(args, attr, None)
    if value is not None:
        return value
    return config.get(attr, default)


def _bool_arg(value: str) -> bool:
    lowered = value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    raise argparse.ArgumentTypeError("expected true or false")


def _required_config_value(args: argparse.Namespace, config: dict, attr: str, label: str):
    value = _config_value(args, config, attr)
    if value is None:
        raise SystemExit(f"ERROR: {label} is required or must be set in run_config.json")
    return value


def _optional_config_list(config: dict, key: str) -> list | None:
    if key not in config or config[key] is None:
        return None
    if not isinstance(config[key], list):
        raise SystemExit(f"ERROR: run_config.json field {key!r} must be a list")
    return config[key]


def _optional_config_int(config: dict, key: str) -> int | None:
    if key not in config or config[key] is None:
        return None
    if not isinstance(config[key], int):
        raise SystemExit(f"ERROR: run_config.json field {key!r} must be an integer")
    return int(config[key])


def _optional_config_float(config: dict, key: str) -> float | None:
    if key not in config or config[key] is None:
        return None
    if not isinstance(config[key], (int, float)):
        raise SystemExit(f"ERROR: run_config.json field {key!r} must be numeric")
    return float(config[key])


RUN_CONFIG_KEYS = {
    "model_name",
    "image",
    "gpu",
    "tp_size",
    "timeout",
    "batch_sizes",
    "max_new_tokens",
    "supplemental_runs",
    "max_captures_per_target",
    "disable_cuda_graph",
    "enable_piecewise_cuda_graph",
    "force_flashinfer_backends",
    "mem_fraction_static",
    "cuda_graph_max_bs",
    "engine_kwargs",
}


def _validate_run_config(config: dict) -> None:
    """Reject unsupported or stale run config fields."""
    if "definitions_dir" in config and config["definitions_dir"] is not None:
        raise SystemExit(
            "ERROR: run_config.json field 'definitions_dir' is not allowed in the standard workflow. "
            "Use the run's output/definitions generated by the same-run fitrace dump."
        )
    unknown = sorted(key for key in config if key not in RUN_CONFIG_KEYS and key != "definitions_dir")
    if unknown:
        raise SystemExit(f"ERROR: unsupported run_config.json fields: {unknown}")


def _load_reviewed_json_artifacts(root: Path) -> list[dict]:
    if not root.exists():
        return []
    artifacts: list[dict] = []
    for path in sorted(root.rglob("*.json")):
        relative = path.relative_to(root)
        if any(part in {"", ".", ".."} for part in relative.parts):
            raise SystemExit(f"ERROR: invalid reviewed artifact path: {path}")
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"ERROR: invalid reviewed artifact JSON {path}: {exc}") from exc
        if not isinstance(data, dict):
            raise SystemExit(f"ERROR: reviewed artifact must be a JSON object: {path}")
        artifacts.append({"path": str(relative), "data": data})
    return artifacts


def _reviewed_definition_artifacts(run_dir: Path) -> dict:
    return {
        "definitions": _load_reviewed_json_artifacts(_run_reviewed_definitions_dir(run_dir)),
        "definition_hints": _load_reviewed_json_artifacts(_run_reviewed_definition_hints_dir(run_dir)),
    }


def _read_json_if_exists(path: Path) -> dict | list | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"ERROR: invalid JSON {path}: {exc}") from exc


def _run_report_paths(run_dir: Path) -> tuple[Path, Path]:
    return run_dir / "reports" / "run_report.json", run_dir / "reports" / "review.md"


def _run_workload_manifest_from_report(run_dir: Path) -> dict | None:
    report = _read_run_report(run_dir)
    if not isinstance(report, dict):
        return None
    collect = report.get("collect")
    if not isinstance(collect, dict):
        return None
    manifest = collect.get("manifest")
    return manifest if isinstance(manifest, dict) else None


def _read_run_report(run_dir: Path) -> dict | None:
    report = _read_json_if_exists(_run_report_paths(run_dir)[0])
    return report if isinstance(report, dict) else None


def _add_runtime_override_args(parser: argparse.ArgumentParser) -> None:
    """Add reviewed runtime override flags for run."""
    parser.add_argument("--image")
    parser.add_argument("--gpu")
    parser.add_argument("--tp-size", type=int)
    parser.add_argument("--max-new-tokens", type=int)
    parser.add_argument("--disable-cuda-graph", type=_bool_arg)
    parser.add_argument("--resume-call-id", help="Reattach to an existing Modal function call.")


def _add_run_parser(subparsers: argparse._SubParsersAction) -> None:
    parser = subparsers.add_parser(
        "run",
        help="Run Modal probing and optional remote collect using the reviewed run config.",
    )
    parser.add_argument("--run", required=True, help="Run path under runs/. Slash-separated names create nested run roots.")
    parser.add_argument("--model-name")
    _add_runtime_override_args(parser)
    parser.add_argument("--timeout", type=int)
    parser.add_argument(
        "--diagnostic-full-scan",
        action="store_true",
        help="Debug only: keep running after early sanitize/audit failures to collect more diagnostics.",
    )


def _add_validate_parser(subparsers: argparse._SubParsersAction) -> None:
    parser = subparsers.add_parser(
        "validate",
        help="Run internal consistency checks, export the dataset, and run upstream validation.",
    )
    parser.add_argument("--run", required=True, help="Run path under runs/. Slash-separated names create nested run roots.")


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _build_internal_validation(
    *,
    approved_targets_path: Path,
    definitions_dir: Path,
    parse_report: dict | None,
    workload_manifest_path: Path | None,
    workload_manifest: dict | None = None,
) -> dict:
    return validate_run(
        approved_targets_path=approved_targets_path,
        definitions_dir=definitions_dir,
        parse_report=parse_report,
        workload_manifest_path=workload_manifest_path,
        workload_manifest=workload_manifest,
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser."""
    parser = argparse.ArgumentParser(description="Minimal FlashInfer trace core")
    subparsers = parser.add_subparsers(dest="command", required=True)
    _add_run_parser(subparsers)
    _add_validate_parser(subparsers)
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the CLI."""
    args = build_parser().parse_args(argv)

    if args.command == "run":
        run_dir = _run_dir_from_name(args.run)
        config = _load_run_config(run_dir)
        _validate_run_config(config)
        approved_targets = _run_config_dir(run_dir) / "approved_targets.json"
        if not approved_targets.exists():
            raise SystemExit(f"ERROR: approved targets not found: {approved_targets}")

        model_name = _required_config_value(args, config, "model_name", "--model-name")
        definitions_dir = _run_output_dir(run_dir) / "definitions"
        image = _required_config_value(args, config, "image", "--image")
        gpu = _required_config_value(args, config, "gpu", "--gpu")
        tp_size = int(_required_config_value(args, config, "tp_size", "--tp-size"))
        output_dir = _run_modal_tmp_dir(run_dir)

        timeout = int(_config_value(args, config, "timeout", 3600))
        max_new_tokens = (
            args.max_new_tokens
            if args.max_new_tokens is not None
            else config.get("max_new_tokens")
        )
        plan = build_modal_probe_plan(
            probe_plan=build_probe_plan(load_approved_targets(approved_targets)),
            model_name=model_name,
            output_dir=output_dir,
            image=str(image),
            gpu=str(gpu),
            tp_size=tp_size,
            batch_sizes=_optional_config_list(config, "batch_sizes"),
            max_new_tokens=int(max_new_tokens) if max_new_tokens is not None else None,
            supplemental_runs=_optional_config_list(config, "supplemental_runs"),
            max_captures_per_target=_optional_config_int(config, "max_captures_per_target"),
            disable_cuda_graph=_config_value(args, config, "disable_cuda_graph"),
            enable_piecewise_cuda_graph=config.get("enable_piecewise_cuda_graph"),
            force_flashinfer_backends=config.get("force_flashinfer_backends"),
            mem_fraction_static=_optional_config_float(config, "mem_fraction_static"),
            cuda_graph_max_bs=_optional_config_int(config, "cuda_graph_max_bs"),
            engine_kwargs=config.get("engine_kwargs"),
        )
        if args.diagnostic_full_scan:
            plan["diagnostics"] = {"full_scan": True}
        plan["reviewed_artifacts"] = _reviewed_definition_artifacts(run_dir)
        shutil.rmtree(output_dir, ignore_errors=True)
        output_dir.mkdir(parents=True, exist_ok=True)

        summary = plan["probe_plan"]["summary"]
        runtime = plan["runtime"]
        print(f"run: {args.run}")
        print(f"probe targets: {summary['targets']}")
        print(f"skipped entries: {summary['skipped']}")
        print(
            f"runtime: gpu={runtime['gpu']} tp={runtime['tp_size']} "
            f"image={runtime['image']} sources={runtime['sources']}"
        )
        print(f"max captures per target: {plan.get('capture_limits', {}).get('max_captures_per_target', 0)}")
        print(f"definitions dir: {definitions_dir}")
        print("collect: remote fitrace")
        print("probe plan: generated for Modal")
        if args.diagnostic_full_scan:
            print("diagnostic full scan: enabled")

        modal_result = run_modal_probe(
            modal_probe_plan=plan,
            output_dir=output_dir,
            timeout=timeout,
            resume_call_id=args.resume_call_id,
        )
        shutil.rmtree(output_dir, ignore_errors=True)
        parse_report = modal_result.get("parse_report")
        if not isinstance(parse_report, dict):
            raise SystemExit("ERROR: remote run did not return parse_report")

        remote_summary = modal_result.get("summary", {})
        remote_report = {"summary": remote_summary}
        if isinstance(modal_result.get("early_stop"), dict):
            remote_report["early_stop"] = modal_result["early_stop"]
        print(f"remote hooks installed: {remote_summary.get('hooks_installed', 0)}")
        print(f"worker processes: {remote_summary.get('worker_processes', 0)}")
        print(f"worker hooks installed: {remote_summary.get('worker_hooks_installed', 0)}")
        print(f"remote events: {remote_summary.get('events_written', 0)}")
        print("parse report: reports/run_report.json#parse_report")

        collect_plan = modal_result.get("collect_plan")
        if not isinstance(collect_plan, dict):
            collect_plan = None
        manifest = modal_result.get("workload_manifest")
        if isinstance(manifest, dict):
            if collect_plan is None:
                raise SystemExit(
                    "ERROR: remote collect returned a workload manifest but no collect plan. "
                    "Check the Modal result materialization before validating this run."
                )
            print("collect source: remote")
        else:
            raise SystemExit(
                "ERROR: remote collect was enabled but no workload manifest was returned. "
                "Check the Modal result, fitrace dump, and definition audit under the run directory; "
                "then rerun the reviewed workflow after fixing the source problem."
            )
        update_run_report(
            run_dir,
            remote=remote_report,
            parse_report=parse_report,
            collect={"plan": collect_plan, "manifest": manifest},
        )
        definition_audit = modal_result.get("definition_audit_report")
        if isinstance(definition_audit, dict):
            update_run_report(run_dir, definition_audit=definition_audit)
        print(f"workload manifests: {manifest['summary']['workloads']}")
        print(f"workload skipped: {manifest['summary']['skipped']}")
        print(f"capture files: {manifest['summary'].get('captures', 0)}")
        print(f"workload files: {manifest['summary'].get('workload_files', 0)}")
        print(f"manifest: {_run_report_paths(run_dir)[0]}")

        report = _build_internal_validation(
            approved_targets_path=approved_targets,
            definitions_dir=definitions_dir,
            parse_report=parse_report,
            workload_manifest_path=None,
            workload_manifest=manifest,
        )
        update_run_report(run_dir, internal_validation=report)
        validate_summary = report["summary"]
        print(f"validation ok: {validate_summary['ok']}")
        print(f"errors: {validate_summary['errors']}")
        print(f"warnings: {validate_summary['warnings']}")
        run_report_path, run_review_path = _run_report_paths(run_dir)
        print(f"run report: {run_report_path}")
        print(f"review: {run_review_path}")
        return 0 if validate_summary["ok"] else 1

    if args.command == "validate":
        run_dir = _run_dir_from_name(args.run)
        config = _load_run_config(run_dir)
        _validate_run_config(config)
        approved_targets = _run_config_dir(run_dir) / "approved_targets.json"
        definitions_dir = _run_output_dir(run_dir) / "definitions"
        workload_manifest = _run_workload_manifest_from_report(run_dir)
        run_report = _read_run_report(run_dir) or {}
        parse_report = run_report.get("parse_report") if isinstance(run_report.get("parse_report"), dict) else None
        report = _build_internal_validation(
            approved_targets_path=approved_targets,
            definitions_dir=definitions_dir,
            parse_report=parse_report,
            workload_manifest_path=None,
            workload_manifest=workload_manifest,
        )
        update_run_report(run_dir, internal_validation=report)
        internal_summary = report["summary"]
        print(f"internal validation ok: {internal_summary['ok']}")
        print(f"errors: {internal_summary['errors']}")
        print(f"warnings: {internal_summary['warnings']}")
        run_report_path, run_review_path = _run_report_paths(run_dir)
        print(f"run report: {run_report_path}")
        print(f"review: {run_review_path}")
        if not internal_summary["ok"]:
            print("run accepted: False")
            return 1

        official_dir = run_dir / "reports" / "official_validate_artifacts"
        export_report = export_run_dataset(
            run_dir=run_dir,
            output_dir=_run_output_dir(run_dir),
            overwrite=False,
        )
        update_run_report(run_dir, export=export_report)
        export_summary = export_report["summary"]
        print(f"dataset: {export_report['dataset_dir']}")
        print(f"definitions: {export_summary['definitions']}")
        print(f"missing definitions: {export_summary['missing_definitions']}")
        if not export_summary["ok"]:
            print("run accepted: False")
            return 1

        official_report = run_official_validate(
            dataset_dir=_run_output_dir(run_dir),
            output_dir=official_dir,
            checks="layout,definition,workload",
            outputs="stdout,json,text",
            output_folder=None,
            disable_gpu=True,
        )
        update_run_report(run_dir, official_validation=official_report)
        print(f"official validation ok: {official_report['ok']}")
        print(f"returncode: {official_report['returncode']}")
        print(f"run report: {run_report_path}")
        print(f"run accepted: {official_report['ok']}")
        return 0 if official_report["ok"] else 1

    raise AssertionError(f"unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
